from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
import sys


app = QtWidgets.QApplication(sys.argv)
screen = app.primaryScreen()
size = screen.size()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        

        screen_width = size.width()
        screen_height = size.height()
        width = int(screen_width * 0.45)
        height = int(screen_height * 0.324)
        MainWindow.resize(width, height)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.apply_btn = QtWidgets.QPushButton(self.centralwidget)
        window_width = MainWindow.width()
        window_height = MainWindow.height()

        btn_x = int(window_width * 0.036)
        btn_y = int(window_height * 0.743)
        btn_w = int(window_width * 0.0857)
        btn_h = int(window_height * 0.0886)

        self.apply_btn.setGeometry(QtCore.QRect(btn_x, btn_y, btn_w, btn_h))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.apply_btn.setFont(font)
        self.apply_btn.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.apply_btn.setObjectName("apply_btn")
        self.depth_cb = QtWidgets.QComboBox(self.centralwidget)
        self.depth_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.depth_cb.setObjectName("depth_cb")
        self.ore_type_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.ore_type_cb.setFont(font)
        self.ore_type_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.dip_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.dip_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.dip_cb.setObjectName("dip_cb")
        self.strength_of_ore_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.strength_of_ore_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.strength_of_ore_cb.setObjectName("strength_of_ore_cb")
        self.strength_of_country_rock_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.strength_of_country_rock_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.distribution_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.distribution_cb.setFont(font)
        self.distribution_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.thickness_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.thickness_cb.setAccessibleName("")
        self.thickness_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.thickness_cb.setCurrentText("")
        self.thickness_cb.setObjectName("thickness_cb")
        self.shape_cb = QtWidgets.QComboBox(self.centralwidget)
        
        self.shape_cb.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.shape_cb.setObjectName("shape_cb")
        self.strength_of_country_rock_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.strength_of_country_rock_lb.setFont(font)
        self.strength_of_country_rock_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.strength_of_country_rock_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.distribution_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.distribution_lb.setFont(font)
        self.distribution_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distribution_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.dip_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.dip_lb.setFont(font)
        self.dip_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dip_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.dip_lb.setObjectName("dip_lb")
        self.depth_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.depth_lb.setFont(font)
        self.depth_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.depth_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.depth_lb.setObjectName("depth_lb")
        self.shape_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.shape_lb.setFont(font)
        self.shape_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shape_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.shape_lb.setObjectName("shape_lb")
        self.strength_of_ore_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.strength_of_ore_lb.setFont(font)
        self.strength_of_ore_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.strength_of_ore_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.strength_of_ore_lb.setObjectName("strength_of_ore_lb")
        self.thickness_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.thickness_lb.setFont(font)
        self.thickness_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thickness_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.thickness_lb.setObjectName("thickness_lb")
        self.ore_type_lb = QtWidgets.QLabel(self.centralwidget)
        
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.ore_type_lb.setFont(font)
        self.ore_type_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ore_type_lb.setAlignment(QtCore.Qt.AlignLeft)
        self.pic_lbl = QtWidgets.QLabel(self.centralwidget)
        
        self.pic_lbl.setAutoFillBackground(True)
        self.pic_lbl.setText("")
        self.pic_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.pic_lbl.setPixmap(QtGui.QPixmap(""))
        self.pic_lbl.setScaledContents(True)
        self.pic_lbl.setObjectName("label")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        btn2_x = int(MainWindow.width() * 0.329)
        btn2_y = int(MainWindow.height() * 0.743)
        btn2_w = int(MainWindow.width() * 0.0857)
        btn2_h = int(MainWindow.height() * 0.0886)

        self.next_btn.setGeometry(QtCore.QRect(btn2_x, btn2_y, btn2_w, btn2_h))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(int(height * 0.032))
        font.setBold(True)
        font.setWeight(QFont.Bold)
        self.next_btn.setHidden(True)
        self.next_btn.setFont(font)
        self.shape_cb.setFont(font)
        self.depth_cb.setFont(font)
        self.thickness_cb.setFont(font)
        self.dip_cb.setFont(font)
        self.strength_of_country_rock_cb.setFont(font)
        self.strength_of_ore_cb.setFont(font)

        w = MainWindow.width()
        h = MainWindow.height()
        self.depth_cb.setGeometry(int(w*0.036), int(h*0.257), int(w*0.25), int(h*0.085))
        self.ore_type_cb.setGeometry(int(w*0.036), int(h*0.6), int(w*0.25), int(h*0.085))
        self.dip_cb.setGeometry(int(w*0.329), int(h*0.091), int(w*0.25), int(h*0.085))
        self.strength_of_ore_cb.setGeometry(int(w*0.329), int(h*0.257), int(w*0.25), int(h*0.085))
        self.strength_of_country_rock_cb.setGeometry(int(w*0.329), int(h*0.431), int(w*0.25), int(h*0.085))
        self.distribution_cb.setGeometry(int(w*0.329), int(h*0.6), int(w*0.25), int(h*0.085))
        self.thickness_cb.setGeometry(int(w*0.036), int(h*0.428), int(w*0.25), int(h*0.085))
        self.shape_cb.setGeometry(int(w*0.036), int(h*0.091), int(w*0.25), int(h*0.085))

        self.strength_of_country_rock_lb.setGeometry(int(w*0.329), int(h*0.343), int(w*0.9), int(h*0.085))
        self.distribution_lb.setGeometry(int(w*0.329), int(h*0.515), int(w*0.3), int(h*0.085))
        self.dip_lb.setGeometry(int(w*0.329), int(h*0.011), int(w*0.143), int(h*0.085))
        self.depth_lb.setGeometry(int(w*0.036), int(h*0.175), int(w*0.2), int(h*0.085))
        self.shape_lb.setGeometry(int(w*0.036), int(h*0.0085), int(w*0.2), int(h*0.085))
        self.strength_of_ore_lb.setGeometry(int(w*0.329), int(h*0.175), int(w*0.214), int(h*0.085))
        self.thickness_lb.setGeometry(int(w*0.036), int(h*0.343), int(w*0.2), int(h*0.085))
        self.ore_type_lb.setGeometry(int(w*0.036), int(h*0.514), int(w*0.2), int(h*0.085))

        self.pic_lbl.setGeometry(int(w*0.625), int(h*0.085), int(w*0.350), int(h*0.700))
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shape_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.depth_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.thickness_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dip_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.strength_of_country_rock_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.strength_of_ore_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.distribution_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ore_type_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("background-color: #32CC99; border-radius:5px ; color:white;")
        self.next_btn.setObjectName("next_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apply_btn.setText(_translate("MainWindow", "Apply"))
        self.strength_of_country_rock_lb.setText(_translate("MainWindow", "Strength Of Country Rock"))
        self.dip_lb.setText(_translate("MainWindow", "Dip"))
        self.distribution_lb.setText(_translate("MainWindow", "Ore Grade Distribution"))
        self.depth_lb.setText(_translate("MainWindow", "Depth"))
        self.shape_lb.setText(_translate("MainWindow", "Orebody Shape"))
        self.strength_of_ore_lb.setText(_translate("MainWindow", "Strength Of Ore"))
        self.thickness_lb.setText(_translate("MainWindow", "Thickness"))
        self.ore_type_lb.setText(_translate("MainWindow", "Ore Type"))
        self.next_btn.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
